### ISSUE TITLE
Will the GPT-4 evaluator used in VisIT-Bench be released?

### ISSUE THREAD

**Issue by BellXP** [mlfoundations/VisIT-Bench#1]
Firstly, I really appreciate your outstanding contribution to the LVLM field. Now we are doing some work on the LVLM model and it's imperative for us to evaluate our model's performance in time. As the performance score in VisIT-Bench is obtained by a GPT-4 evaluator, will you have a plan to release this score calculation code?

**Comment by Hritikbansal** [comment]
Hi,

Thanks for your kind words.

In its current form, VisIT-Bench is purely a test dataset, which means that we are releasing the input to the instances only. We do not provide human-verified GPT-4 response and our evaluator code now. Once you are ready with your final LVLM model, feel free to send us your prediction files and we will add your model to our leaderboard. 

Creating a validation set for VisIT-Bench that can help the model builders to analyze their mistakes is a direction that future iterations of our work will aim to address.
