### ISSUE TITLE
Questions about the dataset

### ISSUE THREAD

**Issue by zzk1st** [mlfoundations/VisIT-Bench#4]
Hi VisIT-Bench team,

Thanks for the great work! We are trying to use the dataset to evaluate our model, and we have two questions:
- it seems 50% of the examples in the dataset doesn't have a reference answer. Do you know why and when we could have full reference answers?
- Will the conditioned image caption be provide sometime in the future?

Thanks in advance!

**Comment by Hritikbansal** [comment]
Hi, 
1. 50% of the examples in the dataset doesn't have a reference answer -- we are sorry for the confusion but the reference_output column is not the same as human-verified response. It is not a useful column and we will remove it soon from the dataset. Thanks for catching the mistake.
2. We are working on providing a subset of the data as validation data for model development. The val data will have the instruction-conditioned caption + human-verified outputs that are currently hidden.

 Tagging @yonatanbitton @jmhessel to be on the same page.

**Comment by Hritikbansal** [comment]
Hi @zzk1st , 

We released the full dataset (gpt4 reference answer + instruction-conditioned captions) at https://huggingface.co/datasets/mlfoundations/VisIT-Bench.
